config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'

  resources :lists, only: %I[index show new create] do
    resources :bookmarks, only: %I[new create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = @list ? @list.bookmarks.new : Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = @list.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to @bookmark.list
    else
      @movies = Movie.all
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to @bookmark.list
  end

  private

  def set_list
    @list = List.find(params[:list_id]) if params[:list_id]
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path, notice: 'Your list was successfully created!'
    else
      render :new, status: 422
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="border p-4">
        <%= simple_form_for [list, bookmark] do |f| %>
          <div class="mb-3">
            <label for="bookmark_movie_id" class="form-label">Select a movie:</label>
            <%= f.collection_select :movie_id, @movies, :id, :title, { prompt: true }, class: "form-select" %>
          </div>
          <div class="mb-3">
            <%= f.input :comment, label: "Comment" %>
          </div>

          <% if @bookmark.movie.present? %>
            <%= f.hidden_field :poster_url, value: @bookmark.movie.poster_url %>
            <%= f.hidden_field :rating, value: @bookmark.movie.rating %>
            <%= f.hidden_field :overview, value: @bookmark.movie.overview %>
          <% end %>

          <%= f.submit "Save", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
      <div class="container-fluid mx-0 px-0">
        <%= link_to lists_path do %>
          <img src="https://imagensemoldes.com.br/wp-content/uploads/2020/06/Movie-Logo-Cinema-PNG.png" alt="Bootstrap" style="padding: 15px" width="130px" height="130px">
        <% end %>
        <figure class="m-0" style="margin-right: 20px !important;">
          <blockquote class="blockquote">
            <h1>Cinefile Log</h1>
          </blockquote>
          <figcaption class="blockquote-footer">
            Feed your soul.
          </figcaption>
        </figure>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1574267432553-4b4628081c31?q=80&w=3131&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>List your movies and never forget one again</h1>
    <p>Create lists like terror, romance, or Friday night picks. Your pick, your decision!</p>
    <%= link_to "Create a new list", new_list_path, class: "btn btn-secondary" %>
  </div>
</div>

<div class="d-flex justify-content-start">
  <h3 style="margin-left: 150px; margin-top: 30px">Lists (<%= @lists.length %>) </h3>
</div>

<div class="cards cards_container mt-2">
  <% @lists.each do |l| %>
    <div class="card-category my-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
      <%= link_to l.name, list_path(l), class: "text-decoration-none text-white", style: "display: block;" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1574267432553-4b4628081c31?q=80&w=3131&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1 class="my-3">Add a new list</h1>
    <%= simple_form_for(@list) do |l| %>
      <%= l.input :name, placeholder: "Add your list name here", label: false %>
      <%= l.submit "Create List", class: "btn btn-success mt-3" %>
    <% end %>
    <%= link_to "See your lists", lists_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="card_banner position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
  <div class="position-absolute top-50 start-50 translate-middle">
    <%= @list.name %>
  </div>
  <div class="position-absolute top-0 end-0 m-4">
    <h4><%= @list.movies.length %> movies</h4>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="d-flex justify-content-end p-5">
      <button class="btn btn-success" onclick="scrollToSection()">Add a Bookmark</button>
    </div>
  </div>
</div>

<div class="container">
  <div class="row row-cols-3 d-flex justify-content-center grid gap-3 column-gap-3">
    <% @list.bookmarks.each do |b| %>
      <div class="col card position-relative" style="width: 18rem; border: none;">
        <div class="position-absolute top-0 end-0 p-3 delete-icon" style="opacity: 0.5;">
          <%= form_with(model: b, url: bookmark_path(b), method: :delete, local: true) do |form| %>
            <button type="submit" class="btn btn-link"><i class="fa-solid fa-trash-can" style="color: #aaadb1;"></i></button>
          <% end %>
        </div>
        <div class="card-img-container mt-2" style="height: 400px; display: flex; justify-content: center; align-items: center; overflow: hidden; border-radius: 5px;">
          <img src="<%= b.movie.poster_url %>" class="card-img-top" style="height: 100%; object-fit: cover; margin-top: 0.5rem;" alt="<%= b.movie.title %>">
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <strong><%= b.movie.title %></strong> -
            <i class="fa-solid fa-star" style="color: #FFD43B;"></i>
            <span style="font-size: smaller; color: grey; font-weight: bold"><%= b.movie.rating.to_i %></span>
          </h5>
          <p class="card-text" style="line-height: 1.5em; max-height: 12em; overflow: hidden; text-overflow: ellipsis;"><%= b.movie.overview %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><i class="fa-solid fa-quote-left fa-sm" style="color: #474748;"></i> <%= b.comment %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>


<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div id="section-to-scroll-to" class="m-6 text-left">
        <%= render 'bookmarks/form', bookmark: @bookmark, movies: @movies, list: @list %>
      </div>
    </div>
  </div>
</div>

<script>
  function scrollToSection() {
    // Scroll smoothly to the section
    document.getElementById('section-to-scroll-to').scrollIntoView({ behavior: 'smooth' });
  }
</script>